### ISSUE TITLE
.dll file stays loaded/doesn't get deleted when installer closes

### ISSUE THREAD

**Issue by endritlim** [negrutiu/nsis-nscurl#15] opened 2024-04-23 07:36 UTC
I use the NScurl plugin to download a file like this:

```
NScurl::http GET "$5" "$6" /SILENT /CANCEL /INSIST /TIMEOUT 30s /CACERT "${TEMP_DIR}\cacert.pem" /RETURN "@ERRORTYPE@:@ERRORCODE@" /END
```

Everything works fine, but the plugin remains in $PLUGINSDIR even after the installer is finished. All the other files from that folder get removed correctly. 

I also tried deleting the folder by myself using

```
SetOutPath $TEMP
RMDir /r $PLUGINSDIR
```
on the .onGUIEnd function, but it doesn't work as well.
The only thing that works is setting the /REBOOTOK flag and then rebooting to completely remove it, which is fine, though I'd like to remove it without a reboot, if possible.

**Comment by negrutiu** [comment] 2024-04-30 19:05
This is a known issue and there is no working solution for it yet.

The problem lies in the underlying libcurl framework.
I was forced to block `NScurl.dll` from unloading (and thus creating this issue) because otherwise libcurl might end up crashing. The crash was actually confirmed on older platforms like Windows XP, Vista, etc.

As mentioned in the [curl_global_cleanup](https://curl.se/libcurl/c/curl_global_cleanup.html) documentation, libcurl should not be used in modules that unload dynamically (like `NScurl.dll` does). So, to prevent potential crashes I came up with this "hack" a while ago...

Let's keep this issue opened and keep looking for a fix...
Thanks for reporting!

**Comment by endritlim** [comment] 2024-04-30 19:32
Thank you for answering! 
I'm somewhat relieved because i thought something isn't working right with my installer.
It definitely makes sense the way you handled this, I'll be looking into this as well, maybe we'll come up with a solution for this at some point.

**Comment by mherrera01** [comment] 2024-08-04 21:02
Hi! I also had this issue and I solved it by calling the [FreeLibrary](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-freelibrary) function on the .onGUIEnd callback:
```
Function .onGuIEnd

  ; Get the NScurl module handle
  System::Call "kernel32::GetModuleHandle(t 'NScurl.dll') i .s"
  Pop $0

  ${If} $0 != 0
    ; Free the NScurl module
    System::Call "kernel32::FreeLibrary(i $0) i .s"
    Pop $0
  ${EndIf}

FunctionEnd
```
I don't know if this is the correct procedure but it works! The `NScurl.dll` file is removed along with the TEMP folder and I didn't have any problems/crashes since it was implemented.

**Comment by negrutiu** [comment] 2024-08-05 08:47
@mherrera01: this trick works on recent Windows builds (10, 11) but not on older ones (7, 8)

Here's what happens on Windows 8:
![image](https://github.com/user-attachments/assets/5230a1c1-3c80-4eb8-ab33-bfd9badb9aeb)

**Comment by mherrera01** [comment] 2024-08-05 18:25
That is unfortunate... I only tested the code with Windows 10/11. Maybe on recent versions a silent crash is happening and Windows handles it correctly. But the problem is still there and it has been an [issue](https://github.com/curl/curl/issues/997) since 2016 (a long time ago with no progress as far as I can see).
I understand that the crash happens when you unload the library and there are still libcurl internal threads running. Is there not a way to kill them manually and then call `curl_global_cleanup`?

**Comment by negrutiu** [comment] 2024-08-06 09:41
I'm not convinced that `getaddrinfo_thread` is causing our crash.
I can reproduce it without `getaddrinfo_thread` ever running.
I suspect that the issue (...or multiple issues) lays deep in `openssl`.
I've found this ticket https://github.com/openssl/openssl/issues/24581
...suggesting that similar problems were fixed recently. Waiting for the next openssl build to see what happens

**Comment by mherrera01** [comment] 2024-08-06 16:37
I've never worked with libCurl/OpenSSL so i cannot help much. The info I found that can be related to this issue is how `atexit()` behaves when the library unloads [[Ref]](https://github.com/openssl/openssl/issues/3777#issuecomment-311288067):
> OpenSSL uses atexit() to cleanup after itself. Some OSes will handle this nicely and call the atexit() handler just before the library unloads. Some will not and will call the atexit() handler at process exit, even if the handler has already been unloaded, which leads to a crash. To prevent this issue we forced the OpenSSL libraries to remain loaded until process exit - which was the best of a bad set of options. Mostly this works fine but does cause problems in exactly the scenario you describe, i.e. statically linking an SO to OpenSSL and then trying to dynamically load/unload the SO.

Also, the OpenSSL docs states the following for `OPENSSL_thread_stop()` on [Notes](https://docs.openssl.org/3.0/man3/OPENSSL_init_crypto/#notes) section:
> Similarly this message will also not be sent if OpenSSL is linked statically, and therefore applications using static linking should also call OPENSSL_thread_stop() on each thread. Additionally if OpenSSL is loaded dynamically via LoadLibrary() and the threads are not destroyed until after FreeLibrary() is called then each thread should call OPENSSL_thread_stop() prior to the FreeLibrary() call.

**Edited**:
The libCurl thread-safety docs mentions `OPENSSL_thread_stop()` as well under [Tls > OpenSSL](https://curl.se/libcurl/c/threadsafe.html):
> libcurl may not be able to fully clean up after multi-threaded OpenSSL depending on how OpenSSL was built and loaded as a library. It is possible in some rare circumstances a memory leak could occur unless you implement your own OpenSSL thread cleanup.
For example, on Windows if both libcurl and OpenSSL are linked statically to a DLL or application then OpenSSL may leak memory unless the DLL or application calls OPENSSL_thread_stop() before each thread terminates. If OpenSSL is built as a DLL then it does this cleanup automatically and there is no leak. If libcurl is built as a DLL and OpenSSL is linked statically to it then libcurl does this cleanup automatically and there is no leak (added in libcurl [8.8.0](https://curl.se/changes.html#8_8_0)).

Just in case it can help you. Let's wait to see if version 3.4.0 of OpenSSL solves the problem with the ticket you mentioned.

By the way, thank you for this plugin 🙏. Great work! Nice to see that this repository is still active.

**Comment by negrutiu** [comment] 2024-08-11 17:33
Good news, guys
I think I've found a fix for the unload crash

The issue:
- `openssl` calls `atexit(OPENSSL_cleanup)` to register its automatic cleanup callback (see `openssl/crypto/init.c`)
- `OPENSSL_cleanup` sits in `NScurl.dll` since NScurl is statically linked to openssl
- at runtime `NScurl.dll` gets unloaded by the NSIS plugin framework, `openssl` shuts down, but the `OPENSSL_cleanup` callback remains registered
- at process exit, CRT (C runtime) calls all `atexit` callbacks, which in our case points inside an unloaded module
- process crashes

Notes:
This behavior might differ depending on the OS and/or the compiler
- older platforms (XP, Vista, 7, 8) behave as described above. The process crashes at exit
- newer platforms (10, 11) somehow mitigate the issue. Could be that `atexit` callbacks are called at module-detach instead of process-exit, or they are never called if the target function points to an invalid memory page, or something else...
- the compiler matters too. `NScurl.dll` is officially built with [mingw-w64](https://www.mingw-w64.org) (gcc for windows). The CRT implementation in mingw behaves as described above. The same code compiled with the Microsoft compiler does not crash, not even on older platforms

The fix:
- we now build `openssl` with `-DOPENSSL_NO_ATEXIT` definition, which prevents it from registering the `atexit` cleanup callback
- we call `OPENSSL_cleanup` ourselves, while the plugin is still loaded
- this way we have a predictable unloading behaviour, regardless of the target platform and the compiler we're using

The fix is included in the latest release
NScurl should now unload correctly and the temp directory should be deleted automatically
Please give it a try and see what happens

**Comment by mherrera01** [comment] 2024-08-12 17:13
Yeah @negrutiu it works! The %temp% is now correctly removed without problems. I even try to quit the installer at the middle of a download and all okay.

What a bizarre issue 🤣. Anyway, thank you for the fix.

**Comment by negrutiu** [comment] 2024-08-13 12:15
Cool, thanks for the confirmation. Closing the issue...

**Closed as completed by negrutiu** 2024-08-13 12:15 UTC
